/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zigzak_androidcalcpi_NativeEncrypt */

#ifndef _Included_net_zigzak_androidcalcpi_NativeEncrypt
#define _Included_net_zigzak_androidcalcpi_NativeEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zigzak_androidcalcpi_NativeEncrypt
 * Method:    nativeEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_zigzak_androidcalcpi_NativeEncrypt_nativeEncrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
