/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zigzak_androidcalcpi_NativePi */

#ifndef _Included_net_zigzak_androidcalcpi_NativePi
#define _Included_net_zigzak_androidcalcpi_NativePi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zigzak_androidcalcpi_NativePi
 * Method:    nativeCreate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_net_zigzak_androidcalcpi_NativePi_nativeCreate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_zigzak_androidcalcpi_NativePi
 * Method:    nativeEstimate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_net_zigzak_androidcalcpi_NativePi_nativeEstimate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_zigzak_androidcalcpi_NativePi
 * Method:    nativeEstimateThread
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_net_zigzak_androidcalcpi_NativePi_nativeEstimateThread
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_zigzak_androidcalcpi_NativePi
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_zigzak_androidcalcpi_NativePi_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
